version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagila
    ports:
      - "5432:5432"
    volumes:
      - ./pagila/pagila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./pagila/pagila-data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - demo-net
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - demo-net
    restart: always

  actors-service:
    build: ./actors-service
    container_name: actors-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pagila
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      OTEL_SERVICE_NAME: actors-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - otel-collector
    networks:
      - demo-net

  films-service:
    build: ./films-service
    container_name: films-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pagila
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      OTEL_SERVICE_NAME: films-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      OTEL_METRICS_EXPORTER: otlp
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: none
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - otel-collector
    networks:
      - demo-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - actors-service
      - films-service
    networks:
      - demo-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./observability/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "9464:9464"
    networks:
      - demo-net
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./observability/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    networks:
      - demo-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - tempo
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - demo-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - demo-net

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - ./observability/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - demo-net

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    command: ["-config.file=/etc/promtail/promtail-config.yaml"]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./observability/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    networks:
      - demo-net

networks:
  demo-net:
    name: pagila_demo-net
    driver: bridge

volumes:
  pgdata:
  tempo-data:
  grafana-storage:
