global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  - job_name: 'actors-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['actors-service:8085']

  - job_name: 'films-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['films-service:8086']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
